### ISSUE TITLE
how can i use utf-8 coding nicknames in battle-eye-client?

### ISSUE THREAD

**Issue by LiveDRus** [electronstorm/battle-eye-client#1]
closes

**Comment by electronstorm** [comment]
You really shouldn't be using the #kick command with names. The command allows you to use the player's id as well as their #.

The syntax for the command is:
`#kick name`
`#kick 47114712`
`#kick 3`

**Comment by LiveDRus** [comment]
So, i use DayZ SA, and i can't user #kick "UID", just nicknames. But i fixit =) Before i can use #kick "ASCII nickname", now i can you it with utf8 nicknames.

**Comment by electronstorm** [comment]
> So, i use DayZ SA, and i can't user #kick "UID", just nicknames. But i fixit =) Before i can use #kick "ASCII nickname", now i can you it with utf8 nicknames.

I was not aware that DayZ SA works differently. You can make a pull request with your fix if you'd like to share it.
