### ISSUE TITLE
Trouble with kick players who have incorrect nicknames

### ISSUE THREAD

**Issue by LiveDRus** [electronstorm/battle-eye-client#2]
Hello.
So i can use "#kick admin" and it works fine.
But if player have nickname like that "💕". I need to use "#kick 💕", and it isn't works. 
How can i kick the players with some nicknames through battle-eye-client?

Need utf8 supports in sending commands i think? Thank you so much for reply!
I use DayZ: Standalone. And i can't kick players uses GUID, or ID. It's restricted. I just can kick it use only nicknames.

**Comment by electronstorm** [comment]
The BE protocol itself is specific as ASCII. There is no mention of utf-8 support. Apparently it exists, but I am not aware of any documentation for it.

Here is the specification:
https://www.battleye.com/downloads/BERConProtocol.txt

**Comment by LiveDRus** [comment]
Maybe when you have:

```
  sendCommand: function(command) {
      //console.log("Sending: " + command)
      var buffer = new Buffer(command.length + 2)
      buffer[0] = 0x01
      buffer[1] = 0//this.sequenceNumber;
      for (var i = 0; i < command.length; i++) {
```

Need to use: 

```
  sendCommand: function(command) {
      //console.log("Sending: " + command)
      var buffer = new Buffer(Buffer.byteLength(command, 'utf-8') + 2)
      buffer[0] = 0x01
      buffer[1] = 0//this.sequenceNumber;
      for (var i = 0; i < Buffer.byteLength(command, 'utf-8'); i++) {
```

**Comment by LiveDRus** [comment]
I found the same problem i think in BattleNET for C#:
https://github.com/marceldev89/BattleNET/issues/6

**Comment by LiveDRus** [comment]
So, do you know, how fixit?

**Comment by electronstorm** [comment]
I implemented the protocol as documented by Bohemia Interactive. Unfortunately I can not do anything about functions they have not implemented/not described.

Anyway it appears to only be an issue in non English in DayZ SA (which has become irrelevant). I have updated the Readme to reflect that.
